### PR TITLE
ellipsify function added 

### PR DESCRIPTION
**Pull request by udhaykumarbala**
ellipsify function added to fix the filter chip text from overflowing the space

### CODE REVIEW

**Review by murderteeth — CHANGES_REQUESTED** [review]
Here I prefer using tailwind's `text-ellipsis` css utility class. This way the filter buttons can show a more detailed summary of your settings. 
https://tailwindcss.com/docs/text-overflow#ellipsis

Also consider larger screens. Using a "fixed" ellipsis length makes the buttons look really small.
image
 
 Regarding mobile screens, the toolbar actually allows horizontal scroll on mobile. So you can swipe left and right. This makes sense on mobile where the swipe gesture is more familiar, but not for large screens.

**Comment by murderteeth** [comment]
Hi @udhaykumarbala, how's it going with this?

**Comment by udhaykumarbala** [comment]
Hi @murderteeth, i will be push the pr by tomorrow, sorry for the delay caught up this week

**Comment by murderteeth** [comment]
> Hi @murderteeth, i will be push the pr by tomorrow, sorry for the delay caught up this week

hey no problem, thanks! just checking in.

**Pull request closed without merging**
